import { AuthProvider } from '@/context/auth';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Toaster } from 'react-hot-toast';
import TopNav from '@/components/TopNav';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <AuthProvider>
          <Toaster />
          <TopNav />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
